### ISSUE TITLE
check_agent_expiry does not handle dates correctly

### ISSUE THREAD

**Issue by jarretlavallee** [puppetlabs/ca_extend#6] opened 2021-02-10 18:23 UTC
## Describe the Bug
The `check_agent_expiry` task improperly shows certs are going to expire soon when they have several years left. 

## Expected Behavior
The `check_agent_expiry` should only show certificates that are expired or going to expire in the next 3 months. 

## Steps to Reproduce
1. Generate certificates within 3 months of the current date that expire in several years
2. Run the task
3. Notice that it does not account for the year

## Cert examples

These certs show in the `expired` array in the json output.

```
# /opt/puppetlabs/puppet/bin/openssl x509 -in /etc/puppetlabs/puppet/ssl/ca/signed/server-c.pem -enddate -noout
notAfter=May 6 00:54:51 2025 GMT
# /opt/puppetlabs/puppet/bin/openssl x509 -in /etc/puppetlabs/puppet/ssl/ca/signed/server-b.pem -enddate -noout
notAfter=Jan 22 22:26:44 2024 GMT
# /opt/puppetlabs/puppet/bin/openssl x509 -in /etc/puppetlabs/puppet/ssl/ca/signed/server-a.pem -enddate -noout
notAfter=Apr 16 18:30:43 2025 GMT
```

**Comment by m0dular** [comment] 2021-03-01 21:36
@jarretlavallee Were you messing with your system clock when testing this?  I can't reproduce.  The script should convert the `notAfter` date from the certs and 3 months from now to epoch time before doing the comparison.

**Comment by m0dular** [comment] 2021-03-02 23:54
The code to calculate the expiration date to check against is [here](https://github.com/puppetlabs/ca_extend/blob/a55dcccd6d20324a34701fce32be8763742f00da/tasks/check_agent_expiry.sh#L10-L11).

Code to get the expiration date of each signed cert is [here](https://github.com/puppetlabs/ca_extend/blob/a55dcccd6d20324a34701fce32be8763742f00da/tasks/check_agent_expiry.sh#L22-L33).

I haven't been able to reproduce the behavior or find a logic error that could explain it.  It could be something like portability issues with `date`, but the PE case with these examples was on Ubuntu 20.04, which should have GNU `date`.  Closing this issue for now until we have a concrete reproduction.

**Closed as completed by m0dular** 2021-03-02 23:54 UTC
Labels: bug
